import { BarChart3, Brain, CalendarDays, ChevronLeft, ChevronRight, GraduationCap, LayoutDashboard, Library, Moon, PanelLeft, Search, Settings2, Sun, Target, Timer, Trophy } from "lucide-react";

type Accent = "indigo" | "emerald" | "amber" | "rose" | "cyan";
type SidebarDrawerProps = { activeTab: string; accent: Accent; collapsed: boolean; darkMode: boolean; onNavigate: (tab: string) => void; onToggle: () => void; onSearch: () => void; onThemeToggle: () => void };

const logoGlow: Record<Accent, string> = {
  indigo: "drop-shadow-[0_0_20px_rgba(99,102,241,0.5)] border-indigo-500/40 shadow-[0_0_20px_rgba(99,102,241,0.3)]",
  emerald: "drop-shadow-[0_0_20px_rgba(16,185,129,0.5)] border-emerald-500/40 shadow-[0_0_20px_rgba(16,185,129,0.3)]",
  amber: "drop-shadow-[0_0_20px_rgba(245,158,11,0.5)] border-amber-500/40 shadow-[0_0_20px_rgba(245,158,11,0.3)]",
  rose: "drop-shadow-[0_0_20px_rgba(244,63,94,0.5)] border-rose-500/40 shadow-[0_0_20px_rgba(244,63,94,0.3)]",
  cyan: "drop-shadow-[0_0_20px_rgba(6,182,212,0.5)] border-cyan-500/40 shadow-[0_0_20px_rgba(6,182,212,0.3)]",
};

const items = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "assessment", label: "Interactive Assessment", icon: Target },
  { id: "tutor", label: "Socratic Tutor", icon: Brain },
  { id: "mock-exam", label: "Mock Exam Arena", icon: Trophy },
  { id: "root-cause", label: "Root Cause Analysis", icon: BarChart3 },
  { id: "knowledge-graph", label: "Knowledge Graph", icon: Library },
  { id: "velocity", label: "Velocity Tracking", icon: Timer },
  { id: "spaced-repetition", label: "Spaced Repetition", icon: CalendarDays },
  { id: "planner", label: "Time-Aware Planner", icon: CalendarDays },
  { id: "mistakes", label: "Mistake Library", icon: GraduationCap },
  { id: "settings", label: "Settings & Logs", icon: Settings2 },
];

export function SidebarDrawer({ activeTab, accent, collapsed, darkMode, onNavigate, onToggle, onSearch, onThemeToggle }: SidebarDrawerProps) {
  return <aside className={`sidebar-motion hidden w-16 shrink-0 overflow-hidden border-r border-slate-300 bg-slate-100 transition-all duration-300 ease-in-out dark:border-slate-800 dark:bg-slate-900/80 lg:flex lg:flex-col ${collapsed ? "items-center" : "w-72"}`}>
    {collapsed ? <>
      <div className="flex w-full flex-col items-center border-b border-slate-200 py-4 dark:border-slate-800"><button type="button" onClick={onToggle} title="Open sidebar" aria-label="Open sidebar" className="group relative grid h-10 w-10 place-items-center rounded-lg text-slate-500 transition-all duration-200 ease-in-out hover:bg-slate-100 hover:text-slate-900 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-white"><div className={`grid h-9 w-9 place-items-center overflow-hidden rounded-lg border bg-white/50 backdrop-blur-sm transition-all duration-300 dark:bg-slate-900/50 ${logoGlow[accent]}`}><img src="/1logo.png.jpeg" alt="Academia.ai Logo" className="h-full w-full shrink-0 rounded-[inherit] object-cover transition-all duration-200 ease-in-out group-hover:scale-90 group-hover:opacity-0" /></div><PanelLeft className="absolute h-5 w-5 scale-90 opacity-0 transition-all duration-200 ease-in-out group-hover:scale-100 group-hover:opacity-100" /></button></div>
      <nav className="flex flex-1 flex-col items-center gap-4 overflow-y-auto py-5">{items.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => onNavigate(id)} title={label} aria-label={label} className={`rounded-lg p-2.5 transition ${activeTab === id ? "bg-indigo-50 font-semibold text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300 dark:border-indigo-400" : "text-slate-700 hover:bg-slate-200 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white"}`}><Icon className="h-5 w-5 text-slate-700 dark:text-slate-300" /></button>)}</nav>
      <div className="flex flex-col items-center gap-2 border-t border-slate-300 p-3 dark:border-slate-800"><button type="button" onClick={onThemeToggle} title="Toggle Theme" aria-label="Toggle Theme" className="rounded-lg p-2.5 text-slate-800 transition-colors duration-200 hover:bg-slate-200 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white">{darkMode ? <Moon className="h-5 w-5 text-indigo-700 dark:text-indigo-300" /> : <Sun className="h-5 w-5 text-amber-600" />}</button><button onClick={() => onNavigate("dashboard")} title="Back to overview" aria-label="Back to overview" className="rounded-lg p-2.5 text-slate-800 transition hover:bg-slate-200 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white"><ChevronLeft className="h-5 w-5 text-slate-700 dark:text-slate-300" /></button></div>
    </> : <>
      <div className="flex h-16 items-center gap-3 border-b border-slate-300 px-5 dark:border-slate-800"><div className={`grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-lg border bg-white/50 backdrop-blur-sm transition-all duration-300 dark:bg-slate-900/50 ${logoGlow[accent]}`}><img src="/1logo.png.jpeg" alt="Academia.ai Logo" className="h-full w-full rounded-[inherit] object-cover" /></div><div className="flex min-w-0 flex-1 flex-col overflow-hidden"><h1 className="whitespace-nowrap text-lg font-bold leading-none tracking-wide text-slate-900 dark:text-white">Academia.ai</h1><span className="mt-1 whitespace-nowrap text-[10px] font-semibold uppercase tracking-widest text-slate-500 dark:text-slate-400">LEARNING OS</span></div><button type="button" onClick={onToggle} title="Collapse sidebar" aria-label="Collapse sidebar" className="shrink-0 rounded-md p-1.5 text-slate-700 opacity-80 transition hover:bg-slate-200 hover:text-slate-950 hover:opacity-100 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white"><PanelLeft className="h-4 w-4 text-slate-700 dark:text-slate-300" /></button><button type="button" onClick={onSearch} title="Search (Ctrl+K)" aria-label="Search (Ctrl+K)" className="shrink-0 rounded-md p-1.5 text-slate-700 opacity-80 transition hover:bg-slate-200 hover:text-slate-950 hover:opacity-100 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white"><Search className="h-4 w-4 text-slate-700 dark:text-slate-300" /></button></div>
      <nav className="flex-1 space-y-1 overflow-y-auto p-3">{items.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => onNavigate(id)} title={label} aria-label={label} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition ${activeTab === id ? "bg-indigo-50 font-semibold text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300 dark:border-indigo-400" : "text-slate-800 hover:bg-slate-200 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white"}`}><Icon className="h-4 w-4 shrink-0 text-slate-700 dark:text-slate-300" /><span className="min-w-0 overflow-hidden whitespace-nowrap text-slate-800 dark:text-slate-300">{label}</span></button>)}</nav>
      <div className="border-t border-slate-300 p-3 dark:border-slate-800"><button type="button" onClick={onThemeToggle} title="Toggle Theme" aria-label="Toggle Theme" className="mb-2 flex w-full items-center gap-3 rounded-lg px-3 py-2 text-xs font-medium text-slate-800 transition-colors duration-200 hover:bg-slate-200 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white"><span className="relative flex h-6 w-11 items-center justify-between rounded-full border border-slate-300 bg-slate-200 px-1 dark:border-slate-700 dark:bg-slate-800"><Sun className={`h-3.5 w-3.5 ${darkMode ? "text-slate-400" : "text-amber-500"}`} /><Moon className={`h-3.5 w-3.5 ${darkMode ? "text-indigo-300" : "text-slate-400"}`} /><span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition-all duration-300 dark:bg-slate-200 ${darkMode ? "translate-x-5" : "translate-x-0"}`} /></span><span className="whitespace-nowrap text-slate-800 dark:text-slate-300">Theme</span></button><button onClick={() => onNavigate("dashboard")} title="Back to overview" aria-label="Back to overview" className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs text-slate-800 hover:bg-slate-200 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white"><ChevronLeft className="h-4 w-4 shrink-0 text-slate-700 dark:text-slate-300" />Back to overview<ChevronRight className="ml-auto h-4 w-4 shrink-0 text-slate-700 dark:text-slate-300" /></button></div>
    </>}
  </aside>;
}
